### ISSUE TITLE
find doesn't read Amount

### ISSUE THREAD

**Issue by Rignchen** [CMDred/StringLib#3]
I started testing my split function wich uses your find function to avoid redoing stuff already existing

While testing I wanted to ensure myself that the find function would work fine, however when setting the input to `{"String": "Hello World !", "Find": "l", "Amount": 1}` I got 3 as result and the output was `[2, 3, 9]` wich would be fine if I didn't set the `Amout` to 1, after looking a bit in your find function I saw that the value you read is `n` instead of `Amount`, I tried setting n to 1 and it works, however this doesn't match the documentation

**Comment by SilicatYT** [comment]
Good catch, thank you. I will correct this in the next release
